#!/usr/bin/env bun
/**
 * Generates .claude/agents/REGISTRY.md by walking .claude/agents/**\/*.md
 * and parsing each file's frontmatter. Run on demand — this is a generated
 * catalog, not a hand-maintained manifest (matches this repo's own "render
 * on demand, not per-task" philosophy — see CLAUDE.md Session Continuity).
 *
 * Usage: bun scripts/generate-agent-registry.ts
 */

import { readdir, readFile, writeFile } from 'fs/promises';
import { join, relative, dirname } from 'path';

const AGENTS_DIR = join(import.meta.dir, '..', '.claude', 'agents');
const OUTPUT_FILE = join(AGENTS_DIR, 'REGISTRY.md');

interface AgentEntry {
  path: string;
  department: string;
  name: string;
  description: string;
  tools: string;
  model: string;
}

function parseFrontmatter(content: string): Record<string, string> {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fields: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    const sep = line.indexOf(':');
    if (sep === -1) continue;
    const key = line.slice(0, sep).trim();
    const value = line.slice(sep + 1).trim();
    if (key) fields[key] = value;
  }
  return fields;
}

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await walk(full));
    } else if (entry.name.endsWith('.md') && entry.name !== 'REGISTRY.md') {
      files.push(full);
    }
  }
  return files;
}

async function main() {
  const files = (await walk(AGENTS_DIR)).sort();
  const rows: AgentEntry[] = [];

  for (const file of files) {
    const content = await readFile(file, 'utf-8');
    const fm = parseFrontmatter(content);
    if (!fm.name) continue; // skip non-agent markdown (e.g. stray docs)

    const relPath = relative(AGENTS_DIR, file);
    const department = dirname(relPath) === '.' ? '(root)' : dirname(relPath);

    rows.push({
      path: relPath,
      department,
      name: fm.name,
      description: fm.description || '',
      tools: fm.tools || '',
      model: fm.model || '(unset)',
    });
  }

  rows.sort((a, b) => a.department.localeCompare(b.department) || a.name.localeCompare(b.name));

  const lines: string[] = [
    '# Agent Registry',
    '',
    `Generated by \`bun scripts/generate-agent-registry.ts\` — do not hand-edit, re-run instead.`,
    `${rows.length} agents across ${new Set(rows.map(r => r.department)).size} departments.`,
    '',
    '| Department | Agent | Model | Description |',
    '|---|---|---|---|',
  ];

  for (const row of rows) {
    const desc = row.description.replace(/\|/g, '\\|');
    lines.push(`| ${row.department} | [${row.name}](${row.path}) | ${row.model} | ${desc} |`);
  }

  lines.push('');
  await writeFile(OUTPUT_FILE, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${OUTPUT_FILE} (${rows.length} agents)`);
}

main();
